#spring.profiles.active=dev
server:
  servlet:
    contextPath : /cidades
  port : 8082

#LOG
logging:
  level:
     org:
       springframework :
         web : INFO
       apache:
         http : INFO
     br:
       com:
         sf:
           tiss : INFO


#DataBase
#DataBase
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      show-sql: true


#spring.jpa.hibernate.ddl-auto=

#Configuration Actuator
info:
  app:
    name: Cidade IBGE
    description: Recupera cidades
    version: 0.0.1

management:
  context-path: /management
  port: 9090


