#spring.profiles.active=dev
server.servlet.contextPath=/cidades
server.port=8082
spring.jackson.time-zone=America/Sao_Paulo


#LOG
logging.level.org.springframework.web=INFO
logging.level.org.apache.http=INFO
logging.level.br.com.sf.tiss=INFO


#DataBase
#DataBase
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=

#Configuration Actuator
info.app.name=Cidade IBGE
info.app.description=Recupera cidades
info.app.version=0.0.1

management.context-path=/management
management.port=9090


